
# Site settings
title: Zihan Wei
name: Zihan Wei
subtitle: PhD Student
email: zihanwei@stanford.edu
description: >
  &#127758&#127755&#127806&#127795&#128039 
baseurl: ""
url: "https://zihanwei129.github.io/"
github_username:  zihanwei129
disqus_baseurl: "https://zihanwei129.github.io/"
disqus_shortname: https-zihanwei129-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zihan Wei"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/zihanwei129
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Zihan Wei
    url: https://www.linkedin.com/in/zihan-wei-598803111/
    desc: Connect with me on LinkedIn
    share: true
